## PyTorch AutoGrad

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True)

In [3]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [4]:
y.backward()

In [5]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [6]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
x3.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [8]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)