# PyTorch Tensor Manipulations

In [1]:
import torch

## Tensor Shaping

### reshape: Change Tensor Shape

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


In [5]:
print(x.reshape(12))
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [7]:
print(x.reshape(3, 4))
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [8]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [9]:
print(x.reshape(3, 2, 2, 1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


---
## Squeeze: Remove dimension which has only one element.

In [10]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


In [11]:
## Remove any dimension which has only one element.

print(x.squeeze())

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(x.squeeze().size())

torch.Size([2, 2])


In [13]:
## Remove certain dimension, if it has only one element. if it is not, there would be no change.

print(x.squeeze(0).size())

torch.Size([2, 2])


In [14]:
print(x.squeeze(1).size())

torch.Size([1, 2, 2])


---
## Unsqueeze: Insert dimension at certain index

In [15]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [27]:
print(x.unsqueeze(2).size())
print(x.unsqueeze(-1).size())
print(x.reshape(2, 2, 1).size())

torch.Size([2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])
