<a href="https://colab.research.google.com/github/msmsm104/TIL/blob/main/20220528/2_%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3%E1%84%85%E1%85%A9_%E1%84%91%E1%85%AE%E1%86%AF%E1%84%8B%E1%85%A5%E1%84%87%E1%85%A9%E1%84%82%E1%85%B3%E1%86%AB_%E1%84%89%E1%85%A5%E1%86%AB%E1%84%92%E1%85%A7%E1%86%BC%E1%84%83%E1%85%A2%E1%84%89%E1%85%AE%E1%84%92%E1%85%A1%E1%86%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 학습 목표 

- 머신러닝을 위해서, numpy와 pandas의 사용법을 다시 연습합니다.

- numpy를 사용하여 여러가지 벡터 연산을 연습하고, 실제 데이터 유사도를 계산해봅시다.

### 1. 라이브러리 연습 예제 

[ 필수 RECAP ]

> Numpy : broadcasting, universal function

> Pandas : fancy indexing, categorical variable encoding

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([0,0,0])

In [ ]:
## numpy broadcasting
print(v1 + v2) ## vector addition
print(v1 - v2) ## vector subtraction
print(v1 * v2) ## elementwise multiplication
print(v2 / v1) ## elementwise division

print(v1 + 3) ## broadcasting

[1 2 3]
[1 2 3]
[0 0 0]
[0. 0. 0.]
[4 5 6]


In [ ]:
# data를 불러와 봅니다.
data = 

### 2. 유사도 측정 예제

#### EDA & Preprocessing

- 퀵하게 데이터를 파악하고, 유사도 측정 예시에 알맞게 가공해봅시다.

In [ ]:
## EDA


#### 유사도(Proximity)

1. Euclidean distance

2. Cosine Similarity

In [ ]:
def euclidean_distance():
    
    return

In [ ]:
def cosine_similarity():
    
    return