### Tensor

In [1]:
import torch

In [10]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4],
                        [5, 6]])
ft
ft.size()

torch.Size([3, 2])

In [3]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt
bt.size()

torch.Size([2, 2])

In [5]:
x = torch.FloatTensor(3, 2)
x

tensor([[8.4078e-45, 0.0000e+00],
        [2.1826e-38, 1.4013e-45],
        [2.1826e-38, 1.4013e-45]])

---

### Numpy Compatibility

In [11]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [12]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [13]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


---

### Tensor Type-casting

In [17]:
ft.long()

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [21]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

---

### Get Shape

In [23]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.size()

torch.Size([3, 2, 2])

In [24]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [25]:
print(x.dim())

3


In [26]:
print(len(x.size()))

3


In [28]:
print(x.size(0))

3


In [30]:
print(x.shape[0])

3
