## Linear Layer

In [1]:
import torch

### Raw Linear Layer

In [2]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])


In [3]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [4]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    
    return y

In [5]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])
print(x.size())

torch.Size([4, 3])


In [6]:
y = linear(x, W, b)

In [7]:
y

tensor([[11., 14.],
        [20., 26.],
        [29., 38.],
        [38., 50.]])

## nn.Module

In [8]:
import torch.nn as nn

In [9]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)
        
        
        return y

In [10]:
linear = MyLinear(3, 2)

In [12]:
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [13]:
linear(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

---

### Correct way: nn.Parameter

In [16]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        
        y = torch.matmul(x, self.W) + self.b
        
        return y

In [18]:
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [20]:
linear = MyLinear(3, 2)

y = linear(x)

In [23]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[8.4078e-45, 0.0000e+00],
        [1.6816e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]], requires_grad=True)
Parameter containing:
tensor([2.3694e-38, 2.3694e-38], requires_grad=True)


## nn.Linear

In [24]:
linear = nn.Linear(3, 2)
y = linear(x)

In [25]:
print(y.size())

torch.Size([4, 2])


In [26]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.5619,  0.3707, -0.0301],
        [ 0.3950,  0.0253, -0.0591]], requires_grad=True)
Parameter containing:
tensor([-0.0886, -0.5179], requires_grad=True)


### nn.Module can contain other nn.Module's child classes.

In [27]:
class MyLinear(nn.Module):
    
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        
        y = self.linear(x)
        
        return y

In [28]:
linear = MyLinear(3, 2)

In [29]:
y = linear(x)

In [30]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-0.2305,  0.2501,  0.0841],
        [ 0.2527, -0.1455, -0.2981]], requires_grad=True)
Parameter containing:
tensor([0.0366, 0.5388], requires_grad=True)
