<a href="https://colab.research.google.com/github/msmsm104/TIL/blob/main/20220626/05_05_use_GPU_0626.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [5]:
torch.cuda.FloatTensor(2,2)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [6]:
x = torch.FloatTensor(2, 2)

x

tensor([[-1.1409e-08,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]])

In [7]:
x.cuda()

tensor([[-1.1409e-08,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

In [8]:
d = torch.device('cuda:0')

In [10]:
x.cuda(device=d)

tensor([[-1.1409e-08,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

In [11]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [12]:
x.to(device=d)

tensor([[-1.1409e-08,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [13]:
x = torch.cuda.FloatTensor(2, 2)

In [16]:
x = x.cpu()

In [17]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU

In [18]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [19]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.3049, -0.3077],
        [-0.3840,  0.2554]], requires_grad=True)
Parameter containing:
tensor([0.2102, 0.1718], requires_grad=True)


In [20]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.3049, -0.3077],
        [-0.3840,  0.2554]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.2102, 0.1718], device='cuda:0', requires_grad=True)


## Tricks

In [21]:
x = torch.cuda.FloatTensor(2, 2)

In [22]:
x.new(2, 2)

tensor([[-2.0000,  1.5468],
        [ 0.3840,  0.2554]], device='cuda:0')

In [23]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [24]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [26]:
list(linear.parameters())[0].new(2, 2)

tensor([[ 0.3049, -0.3077],
        [-0.3840,  0.2554]], device='cuda:0')