# Gradient Descent

In [4]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target).requires_grad_(True)

x

tensor([[0.6950, 0.7197, 0.9521],
        [0.1065, 0.4996, 0.3385],
        [0.4921, 0.2137, 0.8907]], requires_grad=True)

In [6]:
mse_loss = nn.MSELoss()

In [7]:
loss = mse_loss(x, target)
loss

tensor(0.1768, grad_fn=<MseLossBackward>)

In [8]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() ## calculate gradients.
    
    x = x - learning_rate * x.grad
    
    x.detach_()
    x.requires_grad_(True)
    
    loss = mse_loss(x, target)
    
    print(f"{iter_cnt}th Loss: {loss}")
    print(x)

1th Loss: 0.10693342983722687
tensor([[0.5628, 0.6042, 0.8072],
        [0.1717, 0.4997, 0.3966],
        [0.5383, 0.3440, 0.8928]], requires_grad=True)
2th Loss: 0.06468811631202698
tensor([[0.4599, 0.5144, 0.6945],
        [0.2224, 0.4998, 0.4418],
        [0.5743, 0.4453, 0.8944]], requires_grad=True)
3th Loss: 0.03913232311606407
tensor([[0.3800, 0.4445, 0.6068],
        [0.2619, 0.4998, 0.4770],
        [0.6022, 0.5242, 0.8956]], requires_grad=True)
4th Loss: 0.023672640323638916
tensor([[0.3177, 0.3902, 0.5386],
        [0.2926, 0.4999, 0.5043],
        [0.6239, 0.5855, 0.8966]], requires_grad=True)
5th Loss: 0.014320486225187778
tensor([[0.2694, 0.3479, 0.4856],
        [0.3165, 0.4999, 0.5256],
        [0.6408, 0.6331, 0.8974]], requires_grad=True)
6th Loss: 0.008663009852170944
tensor([[0.2317, 0.3151, 0.4444],
        [0.3350, 0.4999, 0.5421],
        [0.6540, 0.6702, 0.8979]], requires_grad=True)
7th Loss: 0.005240586120635271
tensor([[0.2024, 0.2895, 0.4123],
        [0.349