<a href="https://colab.research.google.com/github/msmsm104/TIL/blob/main/20220703/Use_GPU_0703.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [8]:
x = torch.FloatTensor(2, 2)

x

tensor([[-1.1333e-09,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [9]:
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [10]:
x = torch.FloatTensor(2, 2)

x

tensor([[-1.1337e-09,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]])

In [11]:
x.cuda()

tensor([[-1.1337e-09,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

In [14]:
d = torch.device('cuda:0')

In [15]:
x.cuda(device=d)

tensor([[-1.1337e-09,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

In [17]:
x.device

device(type='cpu')

In [18]:
x.cuda().device

device(type='cuda', index=0)

---
## Convert to CUDA tensor: to()

In [19]:
x.to(device=d)

tensor([[-1.1337e-09,  0.0000e+00],
        [ 7.0976e+22,  1.0903e+27]], device='cuda:0')

---
## Convert to CPU tensor from CUDA tensor

In [20]:
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[-1.1337e-09,  7.0976e+22],
        [ 1.0903e+27,  1.0903e+27]], device='cuda:0')

In [21]:
x = x.cpu()

x

tensor([[-1.1337e-09,  7.0976e+22],
        [ 1.0903e+27,  1.0903e+27]])

In [22]:
d = torch.device('cpu')
x = x.to(device=d)
x

tensor([[-1.1337e-09,  7.0976e+22],
        [ 1.0903e+27,  1.0903e+27]])

---
## Move model from CPU to GPU

In [23]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [28]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.3895,  0.6596],
        [-0.1169,  0.3330]], requires_grad=True)
Parameter containing:
tensor([ 0.1465, -0.6468], requires_grad=True)


In [29]:
linear = linear.cuda()
print_params(linear)

Parameter containing:
tensor([[ 0.3895,  0.6596],
        [-0.1169,  0.3330]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.1465, -0.6468], device='cuda:0', requires_grad=True)


In [30]:
linear = linear.cpu()
print_params(linear)

Parameter containing:
tensor([[ 0.3895,  0.6596],
        [-0.1169,  0.3330]], requires_grad=True)
Parameter containing:
tensor([ 0.1465, -0.6468], requires_grad=True)


In [31]:
d = torch.device('cuda:0')
linear = linear.to(device=d)

print_params(linear)

Parameter containing:
tensor([[ 0.3895,  0.6596],
        [-0.1169,  0.3330]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.1465, -0.6468], device='cuda:0', requires_grad=True)


---
## Tricks

In [32]:
x = torch.cuda.FloatTensor(2, 2)
x

tensor([[ 0.1465, -0.6468],
        [-0.1169,  0.3330]], device='cuda:0')

In [33]:
x.new(2, 2)

tensor([[ 0.1465, -0.6468],
        [-0.1169,  0.3330]], device='cuda:0')

In [34]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [35]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [41]:
list(linear.parameters())[0].new(2, 2)

tensor([[ 0.3895,  0.6596],
        [-0.1169,  0.3330]], device='cuda:0')